'use client';

import { useRef, useState } from 'react';
import {
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  AreaChart, Area, ScatterChart, Scatter,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
} from 'recharts';
import { Download, Loader2 } from 'lucide-react';

import {
  formatCategoryLabel,
  formatValueByField,
  formatFullValueByField,
  humanizeFieldName,
  truncateLabel,
} from '@/app/components/chartFormat';
import { generateChartReportPDF } from '../lib/chart/generateChartReport';

const COLORS = ['#6366f1', '#22c55e', '#f59e0b', '#ef4444', '#06b6d4', '#a855f7', '#ec4899', '#14b8a6'];

interface ChartSpec {
  chartType: 'bar' | 'line' | 'pie' | 'area' | 'scatter' | 'table';
  title: string;
  data: Record<string, string | number>[];
  xKey: string;
  yKeys: string[];
  description?: string;
  error?: string;
}

function CustomTooltip({ active, payload, label, xKey }: any) {
  if (!active || !payload?.length) return null;
  const row = payload[0]?.payload;
  const title = label ?? row?.[xKey] ?? '—';

  return (
    <div className="rounded-lg border border-border bg-popover px-3 py-2 shadow-lg text-sm">
      <p className="mb-1 font-medium text-popover-foreground">{formatCategoryLabel(title)}</p>
      {payload.map((entry: any, i: number) => (
        <div key={i} className="flex items-center gap-2 text-muted-foreground">
          <span className="h-2 w-2 rounded-full" style={{ backgroundColor: entry.color }} />
          <span>{entry.name || entry.dataKey || 'Value'}:</span>
          <span className="font-medium text-popover-foreground">
            {entry.value !== undefined && entry.value !== null
              ? formatFullValueByField(entry.dataKey, entry.value)
              : '—'}
          </span>
        </div>
      ))}
    </div>
  );
}

function YAxisTick({ x, y, payload, dataKey }: any) {
  return (
    <text x={x} y={y} dy={4} textAnchor="end" fontSize={12} style={{ fill: 'var(--muted-foreground)' }}>
      {formatValueByField(dataKey, payload.value)}
    </text>
  );
}

function XAxisTick({ x, y, payload }: any) {
  const label = truncateLabel(formatCategoryLabel(payload.value), 12);
  return (
    <g transform={`translate(${x},${y})`}>
      <text
        dy={10}
        textAnchor="end"
        fontSize={12}
        style={{ fill: 'var(--muted-foreground)' }}
        transform="rotate(-35)"
      >
        {label}
      </text>
    </g>
  );
}

const chartMargin = { top: 8, right: 16, left: 8, bottom: 36 };
const xAxisProps = {
  tick: <XAxisTick />,
  interval: 0 as const,
  height: 56,
  axisLine: { stroke: 'var(--border)' },
  tickLine: false,
};

function DownloadButton({ onClick, loading }: { onClick: () => void; loading: boolean }) {
  return (
    <button
      onClick={onClick}
      disabled={loading}
      className="flex shrink-0 items-center gap-1.5 rounded-lg border border-border bg-background px-2.5 py-1.5 text-xs font-medium text-muted-foreground transition hover:bg-muted hover:text-foreground disabled:opacity-50"
    >
      {loading
        ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
        : <Download className="h-3.5 w-3.5" />}
      {loading ? 'Generating…' : 'Download report'}
    </button>
  );
}

export function ChartRenderer({ spec }: { spec: ChartSpec }) {
  const chartRef = useRef<HTMLDivElement>(null);
  const [downloading, setDownloading] = useState(false);

  if (!spec) return null;

  if (spec.error) {
    return (
      <div className="my-4 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">
        Couldn't render chart: {spec.error}
      </div>
    );
  }

  const { chartType, title, data, xKey, yKeys, description } = spec;

  if (!data || !Array.isArray(data) || data.length === 0) {
    return (
      <div className="my-4 rounded-xl border border-border bg-muted/40 p-4 text-sm text-muted-foreground">
        No data available for "{title || 'this chart'}".
      </div>
    );
  }

  const handleDownload = async () => {
    if (!chartRef.current || downloading) return;
    setDownloading(true);
    try {
      await generateChartReportPDF({
        chartElement: chartRef.current,
        title,
        description,
        data,
        xKey,
        yKeys,
        chartType,
        sourceNote: 'Generated by Analyst AI · Internal fund database',
      });
    } catch (err) {
      console.error('Failed to generate PDF report:', err);
    } finally {
      setDownloading(false);
    }
  };

  const processedData = chartType === 'pie'
    ? data.map(row => {
        const newRow = { ...row };
        yKeys.forEach(key => {
          const val = row[key];
          if (typeof val === 'string') {
            const numVal = parseFloat(val.replace(/[$,]/g, ''));
            newRow[key] = isNaN(numVal) ? val : numVal;
          }
        });
        return newRow;
      })
    : data;

  if (chartType === 'table') {
    const columns = Object.keys(data[0]);
    return (
      <div className="my-4 overflow-hidden rounded-xl border border-border bg-card">
        <div className="flex items-start justify-between gap-3 border-b border-border px-4 py-3">
          <div>
            <h4 className="font-semibold text-foreground">{title}</h4>
            {description && <p className="mt-0.5 text-sm text-muted-foreground">{description}</p>}
          </div>
          <DownloadButton onClick={handleDownload} loading={downloading} />
        </div>
        <div ref={chartRef} className="overflow-x-auto bg-card">
          <table className="min-w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-muted/50">
                {columns.map((k) => (
                  <th key={k} className="px-4 py-2.5 text-left font-medium text-muted-foreground">
                    {humanizeFieldName(k)}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.map((row, i) => (
                <tr key={i} className={`border-b border-border last:border-0 ${i % 2 === 1 ? 'bg-muted/30' : ''}`}>
                  {columns.map((k) => (
                    <td key={k} className="px-4 py-2.5 font-mono text-foreground">
                      {typeof row[k] === 'number'
                        ? formatFullValueByField(k, row[k] as number)
                        : formatCategoryLabel(row[k])}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  return (
    <div className="my-4 rounded-xl border border-border bg-card p-5">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div>
          <h4 className="font-semibold text-foreground">{title}</h4>
          {description && <p className="mt-0.5 text-sm text-muted-foreground">{description}</p>}
        </div>
        <DownloadButton onClick={handleDownload} loading={downloading} />
      </div>

      <div ref={chartRef} className="bg-card">
        <ResponsiveContainer width="100%" height={340}>
          {chartType === 'bar' ? (
            <BarChart data={processedData} margin={chartMargin}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" />
              <XAxis dataKey={xKey} {...xAxisProps} />
              <YAxis
                tick={(p: any) => <YAxisTick {...p} dataKey={yKeys[0]} />}
                axisLine={false}
                tickLine={false}
                width={56}
              />
              <Tooltip content={<CustomTooltip xKey={xKey} />} cursor={{ fill: 'var(--muted)', opacity: 0.4 }} />
              <Legend verticalAlign="bottom" align="center" wrapperStyle={{ fontSize: 13, paddingTop: 10, color: 'var(--muted-foreground)' }} formatter={(v: string) => humanizeFieldName(v)} />
              {yKeys.map((k, i) => (
                <Bar
                  key={k}
                  dataKey={k}
                  name={humanizeFieldName(k)}
                  fill={COLORS[i % COLORS.length]}
                  radius={[4, 4, 0, 0]}
                  maxBarSize={48}
                />
              ))}
            </BarChart>
          ) : chartType === 'line' ? (
            <LineChart data={processedData} margin={chartMargin}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" />
              <XAxis dataKey={xKey} {...xAxisProps} />
              <YAxis
                tick={(p: any) => <YAxisTick {...p} dataKey={yKeys[0]} />}
                axisLine={false}
                tickLine={false}
                width={56}
              />
              <Tooltip content={<CustomTooltip xKey={xKey} />} />
              <Legend verticalAlign="bottom" align="center" wrapperStyle={{ fontSize: 13, paddingTop: 10, color: 'var(--muted-foreground)' }} formatter={(v: string) => humanizeFieldName(v)} />
              {yKeys.map((k, i) => (
                <Line
                  key={k}
                  type="monotone"
                  dataKey={k}
                  name={humanizeFieldName(k)}
                  stroke={COLORS[i % COLORS.length]}
                  strokeWidth={2.5}
                  dot={{ r: 3 }}
                  activeDot={{ r: 5 }}
                />
              ))}
            </LineChart>
          ) : chartType === 'area' ? (
            <AreaChart data={processedData} margin={chartMargin}>
              <defs>
                {yKeys.map((k, i) => (
                  <linearGradient key={k} id={`grad-${k}`} x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={COLORS[i % COLORS.length]} stopOpacity={0.3} />
                    <stop offset="95%" stopColor={COLORS[i % COLORS.length]} stopOpacity={0} />
                  </linearGradient>
                ))}
              </defs>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" />
              <XAxis dataKey={xKey} {...xAxisProps} />
              <YAxis
                tick={(p: any) => <YAxisTick {...p} dataKey={yKeys[0]} />}
                axisLine={false}
                tickLine={false}
                width={56}
              />
              <Tooltip content={<CustomTooltip xKey={xKey} />} />
              <Legend verticalAlign="bottom" align="center" wrapperStyle={{ fontSize: 13, paddingTop: 10, color: 'var(--muted-foreground)' }} formatter={(v: string) => humanizeFieldName(v)} />
              {yKeys.map((k, i) => (
                <Area
                  key={k}
                  type="monotone"
                  dataKey={k}
                  name={humanizeFieldName(k)}
                  stroke={COLORS[i % COLORS.length]}
                  strokeWidth={2.5}
                  fill={`url(#grad-${k})`}
                />
              ))}
            </AreaChart>
          ) : chartType === 'pie' ? (
            <PieChart margin={{ top: 8, right: 16, left: 8, bottom: 36 }}>
              <Pie
                data={processedData}
                dataKey={yKeys[0]}
                nameKey={xKey}
                outerRadius={110}
                innerRadius={60}
                paddingAngle={2}
                label={({ percent }: any) => `${(percent * 100).toFixed(0)}%`}
                labelLine={false}
              >
                {data.map((_, i) => (
                  <Cell key={i} fill={COLORS[i % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip content={<CustomTooltip xKey={xKey} />} />
              <Legend
                verticalAlign="bottom"
                align="center"
                wrapperStyle={{ fontSize: 13, paddingTop: 10, color: 'var(--muted-foreground)' }}
                formatter={(value: string) => truncateLabel(formatCategoryLabel(value), 22)}
              />
            </PieChart>
          ) : (
            <ScatterChart margin={chartMargin}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
              <XAxis dataKey={xKey} {...xAxisProps} />
              <YAxis
                dataKey={yKeys[0]}
                tick={(p: any) => <YAxisTick {...p} dataKey={yKeys[0]} />}
                axisLine={false}
                tickLine={false}
                width={56}
              />
              <Tooltip content={<CustomTooltip xKey={xKey} />} cursor={{ strokeDasharray: '3 3' }} />
              <Scatter data={processedData} name={humanizeFieldName(yKeys[0])} fill={COLORS[0]} />
            </ScatterChart>
          )}
        </ResponsiveContainer>
      </div>
    </div>
  );
}